services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
      args:
        DOCKER_GID: ${DOCKER_GID}
    container_name: jenkins
    ports:
      - "9091:8080"
      - "50000:50000"
    environment:
      TZ: Asia/Bangkok
      JAVA_OPTS: "-Duser.timezone=Asia/Bangkok"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    group_add:
      - "${DOCKER_GID}"

volumes:
  jenkins_home:
